### ISSUE TITLE
[component]  Header 기능 개발

### ISSUE THREAD

**Issue by muzi55** [muzi55/didit#11]
<img width="371" alt="스크린샷 2024-12-12 오전 2 03 05" src="https://github.com/user-attachments/assets/7349ebe5-2136-4dab-9c75-4e5752964c91" />

헤더 컴포넌트 제작

- [x] #12  헤더 로고
- [x] #19   헤더 로고
- [x] #20  헤더 nav 리스트
- [x] #22  헤더 profile 컴포넌트 
- [ ] #24  헤더 여닫이 기능
